import type { Metadata } from "next";
import Head from 'next/head';
import '../../styles/global/global.css';

export const metadata: Metadata = {
  title: "John 作品集",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-Hant">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </Head>
      <body>
        {children}
      </body>
    </html>
  );
}